version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - depguard
    - err113 # Use errorlint instead.
    - exptostd
    - forbidigo
    - interfacebloat
    - ireturn
    - mnd # deprecated: gomnd was renamed to mnd.
    - modernize
    - nlreturn
    - paralleltest # TODO
    - testableexamples # TODO
    - testpackage
    - tparallel # Use paralleltest instead.
    - wsl
    - wsl_v5
    # Deprecated in v1 and removed in v2 (kept as notes):
    # - exportloopref
    # - execinquery
  settings:
    gosec:
      excludes:
        - G115
    varnamelen:
      max-distance: 15
      ignore-decls:
        - E comparable
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - containedctx
          - contextcheck
          - cyclop
          - dupl
          - forcetypeassert
          - funlen
          - gocognit
          - goconst
          - lll
          - maintidx
          - varnamelen
        path: _test\.go
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
    paths:
      - .*_gen.go$
      - .github
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt # Use gofumpt instead of gofmt.
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*_gen.go$
      - .github
      - third_party$
      - builtin$
      - examples$
